Add reinforce algorithm
SwamyDev/reinforcement pull request #1
Opened 2019-08-26 18:33 UTC by SwamyDev

Reinforce is one of the basic policy gradient algorithm. I've added it
to learn the basics of RL and policy gradient. So far it is just a first
draft and still missing crucial bits like policy approximations and
baseline estimators.

2019-08-27 09:55 UTC, SwamyDev commented on reinforcement/trajectories.py
> +    _ACTIONS = 1
These constants are obsolete

2019-08-27 09:59 UTC, SchwammDev commented on tests/test_reinforce_algorithm.py
> +        losses = [self._calc(sim, a, r) for a, r in zip(batch.actions, batch.returns)]
Should pass in the whole batch (1/NM*Expectation)

2019-08-27 09:59 UTC, SwamyDev commented on reinforcement/algorithm/reinforce.py
> +    return ops.reduce_mean(ops.log(action_dist) * returns)
This is probably wrong, the action probs need to be combined with the actual selected action in some way

2019-08-27 10:02 UTC, SwamyDev commented on tests/test_reinforce_algorithm.py
> +        self._estimates = np.random.uniform(size)
Size & random uniform not needed

2019-09-01 17:13 UTC, Ermelyn commented on tests/test_reinforce_algorithm.py
> +        losses = [self._calc(sim, a, r) for a, r in zip(batch.actions, batch.returns)]
Yes, thats right.

2019-09-01 17:28 UTC, Ermelyn requested changes
Can't say more than you already mentioned.

2019-09-01 18:32 UTC, SwamyDev commented on tests/test_reinforce_algorithm.py
> +        self._estimates = np.random.uniform(size)
Still necessary, but clarified naming

2019-09-01 18:34 UTC, SchwammDev reviewed
Awaiting general reinforcement learning tests.

2019-09-01 18:34 UTC, SwamyDev commented on reinforcement/algorithm/reinforce.py
> +    return ops.reduce_mean(ops.log(action_dist) * returns)
This will be tackled once I've implemented general reinforcement learning tests. These should detect this issue reliably.

2019-09-01 18:34 UTC, SwamyDev commented on tests/test_reinforce_algorithm.py
> +        losses = [self._calc(sim, a, r) for a, r in zip(batch.actions, batch.returns)]
Same as for the reward signal. The next merge should contain tests that hopefully can detect this issue reliably.

2019-09-12 06:17 UTC, SchwammDev reviewed
Fix changes

2019-09-12 06:17 UTC, SwamyDev commented on tests/test_algorithm_learning.py
> +        self._m = np.random.normal(1, 0.001)  # high m avoids local maxima - use negative m for demonstration
```suggestion
        self._m = np.random.normal(1, 0.001)  # high slope avoids local maxima - use negative m for demonstration
```
maybe refer to m as slope in the comment to make it more clear

2019-09-12 06:17 UTC, SwamyDev commented on tests/test_algorithm_learning.py
> +            mp.set_title("m")
```suggestion
            mp.set_title("slope")
```
same here for the string

2019-09-12 06:17 UTC, SwamyDev commented on tests/test_reinforce_algorithm.py
> +def test_fitting_the_approximation_uses_the_correct_loss(policy, baseline, make_trajectory):
rename to reflect that it isn't loss signal anymore

2019-09-12 06:26 UTC, SchwammDev reviewed
Done

2019-09-12 06:36 UTC, merged